### ISSUE TITLE
None type has no attribute split doing date_search

### ISSUE THREAD

**Issue by frank-pet** [python-caldav/caldav#133] opened 2021-01-31 02:15 UTC
Have been successfully using 0.6.2 with the godaddy iCal server.  Upgraded to 0.7.1 and the exceptions hit.   Did some debugging and it seems the server query is returning None instead of the ics content.

**Comment by tobixen** [comment] 2021-01-31 10:06
I did not know godaddy had a caldav server.  I'm trying to register there now and check if I can get caldav access there.

**Comment by tobixen** [comment] 2021-01-31 10:15
Does one have to register for the business office365 email package to get caldav access?  I don't want to cash out for it now ... do you have any possibility to provide me with a test account access?  Credentials can be sent to t-caldav@tobixen.no eventually.

**Comment by frank-pet** [comment] 2021-01-31 10:44
I don’t have the office365 email package—I just a legacy email user with Calder.  I haven’t checked lately if you can sign up for the imap/Calder email calendar as a new user.

**Comment by frank-pet** [comment] 2021-01-31 10:51
I just have the legacy email calendaring.   It appears that as a new user you can only get the Microsoft office version—there currently is a $1.99/month sale just for email (and hopefully calendaring).   If caldav works with the MS servers, perhaps that’s the answer—godaddy has been nagging me to make the migration.

**Comment by tobixen** [comment] 2021-01-31 12:01
As far as I know, Microsoft Office 365 does not support caldav, one has to use some sort of Microsoft Office 365 API for that, I think there exists a python library for it.

I will either need some kind of access to the old caldav interface so I can run the tests towards it, or eventually maybe I will be able to figure out something if you turn on debug logging (it should suffice to do something like this I think:

```
import logging
logging.basicConfig(filename='/tmp/caldav.log', encoding='utf-8', level=logging.DEBUG)
```

**Comment by frank-pet** [comment] 2021-01-31 16:25
attached log outputs for 6.0.2 and 7.0.1  
[caldavdbug.txt](https://github.com/python-caldav/caldav/files/5900098/caldavdbug.txt)

**Comment by tobixen** [comment] 2021-02-04 10:27
I see that the query and the response headers is the same for both 0.6 and 0.7, but somehow the 0.7-code does not recognize the response.

During the last week I've done major refactoring in the code handling the return response from the caldav server, and I've also made it easier to write unit tests for this.  I will now try and write up a unit test including your XML (with a tiny bit of obfuscation).

Please try the master version of caldav and see if the problem can be reproduced there.

**Comment by tobixen** [comment] 2021-02-04 10:49
The problem is that no calendardata is returned, all other calendar server implementations will return calendardata when doing such a date search.  I'm not sure if this is a breach of the standard or not.  At least the current master version should not throw an error, but rather return a list of Events without data (those Events can then eventually be loaded).

Please test.

**Comment by tobixen** [comment] 2021-02-05 08:34
I should add a warning here - the current master branch is littered with assert statements.  I will replace them with error logging before releasing 0.8.  If you try the master version and it fails due to an assert, be quick to raise a new issue (and you may also simply remove the assert line - most likely things will work despite the failed assert).

I'll close this issue as I believe it is resolved (actually it has been resolved in the master branch for a longer time already, when dealing with the sync-token support I added if-statements at that point in the code to deal with the case when no calendar data was returned).

**Closed by tobixen** 2021-02-05 08:34 UTC

**Comment by frank-pet** [comment] 2021-02-07 20:37
First attempt to use the current master, I got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/MessageBoard/dev/caldav/caldav/davclient.py", line 319, in principal
    return Principal(self)
  File "/home/pi/MessageBoard/dev/caldav/caldav/objects.py", line 398, in __init__
    cup = self.get_properties([dav.CurrentUserPrincipal()])
  File "/home/pi/MessageBoard/dev/caldav/caldav/objects.py", line 221, in get_properties
    properties = self._handle_xml_response(response, props)
  File "/home/pi/MessageBoard/dev/caldav/caldav/objects.py", line 192, in _handle_xml_response
    results = response.expand_simple_props(props=props, multi_value_props=multi_value_props)
  File "/home/pi/MessageBoard/dev/caldav/caldav/davclient.py", line 241, in expand_simple_props
    self.find_objects_and_props()
  File "/home/pi/MessageBoard/dev/caldav/caldav/davclient.py", line 177, in find_objects_and_props
    error.assert_(not href in self.objects)
  File "/home/pi/MessageBoard/dev/caldav/caldav/lib/error.py", line 23, in assert_
    assert(condition)
AssertionError

Based on your "littered with assert statements", I then commented out the error.assert on line 177 of davclient.py, and everything seems to work.

Thanks!  

I can open another issue on that if you like.

**Comment by tobixen** [comment] 2021-02-07 21:52
> I can open another issue on that if you like.

Yes please, I'd like to see the XML returned from the server :-)
