### ISSUE TITLE
Ensure compatibility with Xandikos

### ISSUE THREAD

**Issue by direnter** [python-caldav/caldav#40] opened 2019-02-23 23:55 UTC
**Steps to Reproduce**:
```
import caldav

#url = "http://localhost:8080"
#url = "http://:@localhost:8080"
url = "http://localhost:8080/user/calendars/calendar/"

client = caldav.DAVClient(url)
principal = client.principal()
principal.make_calendar(name="Test Calendar")
```

**Expected Result**:
Calendar is created.

**Actual Result**:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 324, in make_calendar
    return self.calendar_home_set.make_calendar(name, cal_id, supported_calendar_component_set=supported_calendar_component_set)
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 335, in calendar_home_set
    chs = self.get_properties([cdav.CalendarHomeSet()])
  File "/usr/lib/python3.7/site-packages/caldav/objects.py", line 192, in get_properties
    raise Exception("The CalDAV server you are using has "
Exception: The CalDAV server you are using has a problem with path handling.
```

**Comment by direnter** [comment] 2019-02-24 00:04
After a discussion with one of the Xandikos devs, the root cause might be that the [exchange path](https://github.com/python-caldav/caldav/blob/v0.5.0.dev/caldav/objects.py#L185) in `get_properties` isn't expecting normalized url paths.

**Comment by direnter** [comment] 2019-02-24 22:11
After further discussion in the Xandikos devs, reopening.

**Comment by tobixen** [comment] 2019-03-08 15:53
Do you have any reference to the discussions? I would also appreciate if it's possible to arrange a testing account on some server that I can use for testing, or a Docker image or a git reference I can use for setting up a server at my end with a test user ready, with 0 configuration effort :)

**Comment by direnter** [comment] 2019-03-09 21:43
The most relevant part of the discussion took place in the #xandikos IRC channel:

[15:26] <jelmer> [14:48] <000000jelmer> NoobSaibot: the short version of it is that there is nothing in the RFCs (that I can find) that says that a principal URL will be normalized by the server by adding a trailing slash to it; python-caldav does expect that slash or it breaks

Right now the best i can do is provide the [Xandikos Test Dockerfile](https://github.com/jelmer/xandikos/blob/master/Dockerfile), but please let me know if there's anything else i can help with.

**Comment by tobixen** [comment] 2019-03-09 21:45
I've just set up a test server, it's based on the Dockerfile.  Tests break as for now, trying to find out if I can understand something.

Test server is running at http://xandikos-caldav-servers.cloudapps.bitbit.net/ ... I guess the password is password1

**Comment by tobixen** [comment] 2019-03-09 21:54
I can reproduce the problem, and I think I have found the issue.  Made a code fix and I'm running the tests now.  I've also joined the IRC channel.  It's bedtime now, so I will probably look into how the tests went and commit tomorrow.

It seems very easy to get the xandikos server up and running at localhost.  Perhaps I can add xandios as a test requirement and fix the test code so it will set up xandios on localhost and run tests towards it ...

**Comment by tobixen** [comment] 2019-03-09 22:03
Now I sent this simple date search query:

```xml
<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV" xmlns:I="http://apple.com/ns/ical/">
  <ns0:prop xmlns:ns0="DAV:">
    <C:calendar-data>
      <C:expand start="20060713T170000Z" end="20060715T170000Z"/>
    </C:calendar-data>
  </ns0:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="20060713T170000Z" end="20060715T170000Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```
... and got this traceback from the server:

```
[pid: 15|app: 0|req: 204/411] 10.1.1.1 () {40 vars in 820 bytes} [Sat Mar  9 21:54:43 2019] PUT /user1/calendars/pav-test/20010712T182145Z-123401@example.com.ics => generated 0 bytes in 51 msecs (HTTP/1.1 201) 1 headers in 74 byitches on core 0)
Traceback (most recent call last):
  File "./xandikos/webdav.py", line 1797, in __call__
    return do.handle(environ, start_response, self)
  File "./xandikos/webdav.py", line 1535, in handle
    app.properties, base_href, r, depth)
  File "./xandikos/webdav.py", line 274, in wrapper
    return _send_dav_responses(start_response, responses, DEFAULT_ENCODING)
  File "./xandikos/webdav.py", line 1285, in _send_dav_responses
    for response in responses:
  File "./xandikos/caldav.py", line 618, in report
    yield webdav.Status(href, '200 OK', propstat=list(propstat))
  File "./xandikos/webdav.py", line 971, in get_properties
    href, resource, properties, environ, propreq)
  File "./xandikos/webdav.py", line 951, in get_property_from_element
    get_value_ext(href, resource, ret, environ, requested)
  File "./xandikos/caldav.py", line 258, in get_value_ext
    extract_from_calendar(calendar, c, requested)
  File "./xandikos/caldav.py", line 233, in extract_from_calendar
    raise AssertionError('invalid element %r' % tag)
AssertionError: invalid element <Element '{urn:ietf:params:xml:ns:caldav}expand' at 0x7f99bc16d408>
[pid: 16|app: 0|req: 208/412] 10.1.1.1 () {42 vars in 762 bytes} [Sat Mar  9 21:54:43 2019] REPORT /user1/calendaraldav-test/ => generated 0 bytes in 12 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
```

Seems like it's complaining about something in the query.  Maybe it's something blatantly obvious, but it's past bedtime here, so I will look into it tomorrow.

**Comment by jelmer** [comment] 2019-03-10 00:23
This is a Xandikos bug; I've filed an issue here: https://github.com/jelmer/xandikos/issues/102

(apparently we haven't come across clients that use CALDAV:expand before)

**Comment by tobixen** [comment] 2019-03-10 10:44
Next issue ...

I'm doing a PUT /user1/calendars/pythoncaldav-test/20010712T182145Z-123401@example.com.ics - in the headers the content type is specified as "text/calendar".  I get a 201 from the server.  Next, I turn around and do a GET on the newly instantiated object.  It fails like this:

```
[pid: 16|app: 0|req: 1577/2979] 10.1.1.1 () {40 vars in 820 bytes} [Sun Mar 10 10:17:09 2019] PUT /user1/calendars/pythoncaldav-test/20010712T182145Z-123401@example.com.ics => generated 0 bytes in 35 msecs (HTTP/1.1 201) 1 headers in 74 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./xandikos/webdav.py", line 1797, in __call__
    return do.handle(environ, start_response, self)
  File "./xandikos/webdav.py", line 1675, in handle
    return _do_get(environ, start_response, app, send_body=True)
  File "./xandikos/webdav.py", line 1694, in _do_get
    accept_content_types, accept_content_languages)
  File "./xandikos/webdav.py", line 693, in render
    accepted_content_types, [self.get_content_type()])
  File "./xandikos/webdav.py", line 109, in pick_content_types
    available_content_types, accepted_content_types)
xandikos.webdav.NotAcceptableError: Unable to convert from content types {'text/calendar'} to one of [('text/xml', {})]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./xandikos/webdav.py", line 1803, in __call__
    return [e.message.encode(DEFAULT_ENCODING)]
AttributeError: 'NotAcceptableError' object has no attribute 'message'
[pid: 15|app: 0|req: 1403/2980] 10.1.1.1 () {36 vars in 753 bytes} [Sun Mar 10 10:17:09 2019] GET /user1/calendars/pythoncaldav-test/20010712T182145Z-123401@example.com.ics => generated 0 bytes in 9 msecs (HTTP/1.1 406) 0 headers in 31 bytes (0 switches on core 0)
```

**Comment by jelmer** [comment] 2019-03-10 21:20
You're attempting to GET a text/calendar object, but while only accepting text/xml responses. Xandikos does not know how to convert text/calendar to text/xml.

**Comment by tobixen** [comment] 2019-03-11 08:05
Thanks, should have spotted that one myself ...

There are still test breakages, though I don't have time to look more into it right now.

**Comment by tobixen** [comment] 2019-03-11 21:14
Another traceback, a propfind on the principal URL failed.

```
caldav: DEBUG: sending request - method=PROPFIND, url=http://xandikos-caldav-servers.cloudapps.bitbit.net/user1/, headers={'User-Agent': 'Mozilla/5.0', 'Content-Type': 'text/xml', 'Accept': 'text/xml, text/calendar', 'Depth': '0'}
body:
<?xml version="1.0" encoding="UTF-8"?><D:propfind xmlns:D="DAV:">  <D:allprop/></D:propfind>
```
Traceback (most recent call last):
  File "./xandikos/webdav.py", line 947, in get_property_from_element
    get_value_ext = prop.get_value_ext
AttributeError: 'PrincipalAddressProperty' object has no attribute 'get_value_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./xandikos/webdav.py", line 1797, in __call__
    return do.handle(environ, start_response, self)
  File "./xandikos/webdav.py", line 273, in wrapper
    responses = req_fn(self, environ, *args, **kwargs)
  File "./xandikos/webdav.py", line 1576, in handle
    ret.append(Status(href, '200 OK', propstat=list(propstat)))
  File "./xandikos/webdav.py", line 1000, in get_all_properties
    ps = get_property_from_name(href, resource, properties, name, environ)
  File "./xandikos/webdav.py", line 920, in get_property_from_name
    href, resource, properties, environ, ET.Element(name))
  File "./xandikos/webdav.py", line 949, in get_property_from_element
    prop.get_value(href, resource, ret, environ)
  File "./xandikos/carddav.py", line 163, in get_value
    resource.get_principal_address(), href))
AttributeError: 'PrincipalBare' object has no attribute 'get_principal_address'
[pid: 15|app: 0|req: 2807/6021] 10.1.1.1 () {42 vars in 698 bytes} [Mon Mar 11 21:04:42 2019] PROPFIND /user1/ => generated
 0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

This breaks towards bedework as well.

**Comment by jelmer** [comment] 2019-03-12 05:16
On Mon, Mar 11, 2019 at 02:14:47PM -0700, Tobias Brox wrote:
> Another traceback, a propfind on the principal URL failed.
> 
> ```
> caldav: DEBUG: sending request - method=PROPFIND, url=http://xandikos-caldav-servers.cloudapps.bitbit.net/user1/, headers={'User-Agent': 'Mozilla/5.0', 'Content-Type': 'text/xml', 'Accept': 'text/xml, text/calendar', 'Depth': '0'}
> body:
> <?xml version="1.0" encoding="UTF-8"?><D:propfind xmlns:D="DAV:">  <D:allprop/></D:propfind>
> ```
> Traceback (most recent call last):
>   File "./xandikos/webdav.py", line 947, in get_property_from_element
>     get_value_ext = prop.get_value_ext
> AttributeError: 'PrincipalAddressProperty' object has no attribute 'get_value_ext'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./xandikos/webdav.py", line 1797, in __call__
>     return do.handle(environ, start_response, self)
>   File "./xandikos/webdav.py", line 273, in wrapper
>     responses = req_fn(self, environ, *args, **kwargs)
>   File "./xandikos/webdav.py", line 1576, in handle
>     ret.append(Status(href, '200 OK', propstat=list(propstat)))
>   File "./xandikos/webdav.py", line 1000, in get_all_properties
>     ps = get_property_from_name(href, resource, properties, name, environ)
>   File "./xandikos/webdav.py", line 920, in get_property_from_name
>     href, resource, properties, environ, ET.Element(name))
>   File "./xandikos/webdav.py", line 949, in get_property_from_element
>     prop.get_value(href, resource, ret, environ)
>   File "./xandikos/carddav.py", line 163, in get_value
>     resource.get_principal_address(), href))
> AttributeError: 'PrincipalBare' object has no attribute 'get_principal_address'
> [pid: 15|app: 0|req: 2807/6021] 10.1.1.1 () {42 vars in 698 bytes} [Mon Mar 11 21:04:42 2019] PROPFIND /user1/ => generated
>  0 bytes in 7 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
> ```
This should be fixed in master now.

What's the best way for me to run the python-caldav testsuite against
Xandikos?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by tobixen** [comment] 2019-03-12 05:37
Clone the library, create a file test/conf_private.py, add something like this there:

```
caldav_servers = []

# Only run tests against my private caldav servers
only_private = True

# Set up the caldav_servers list to point to my xandikos instance running at localhost
caldav_servers.append({
    "url": "http://localhost:8180/",
    "username": "user1",
    "password": "password1",
    "norecurring": True # expanded date_search doesn't work
})
```

Since xandikos is written in python and it's so trivial to spin up a test instance, I'm considering to add xandikos as a test dependency and let the test framework spin up a local instance.

**Comment by jelmer** [comment] 2019-03-13 19:03
Thanks! I'll see if I can run the caldav tests regularly against Xandikos as well.

**Comment by jelmer** [comment] 2019-03-13 19:14
The testsuite now passes against Xandikos master.

**Closed** 2019-05-29 15:10 UTC

**Comment by tobixen** [comment] 2020-05-13 21:47
@jelmer, I tried to remove the "norecurring"-flag from the xandikos testing in the caldav library, and the test still seem to break.  xandikos 0.2.1.  I put in this into the calendar (example from RFC5545):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Example Corp.//CalDAV Client//EN
BEGIN:VEVENT
UID:19970901T130000Z-123403@example.com
DTSTAMP:19970901T130000Z
DTSTART;VALUE=DATE:19971102
SUMMARY:Our Blissful Anniversary
TRANSP:TRANSPARENT
CLASS:CONFIDENTIAL
CATEGORIES:ANNIVERSARY,PERSONAL,SPECIAL OCCASION
RRULE:FREQ=YEARLY
END:VEVENT
END:VCALENDAR
```

and then I do this search:

```
<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:I="http://apple.com/ns/ical/">
  <D:prop>
    <C:calendar-data>
      <C:expand start="20081101T160000Z" end="20081103T160000Z"/>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="20081101T160000Z" end="20081103T160000Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```

I expect to get out a vcalendar object with two vevent objects with same uid but different recurrence-id.

Instead I get nothing (or, more exact: `<multistatus xmlns="DAV:" />)

**Comment by jelmer** [comment] 2020-05-13 23:34
It indeed doesn't support recurring events yet - see https://github.com/jelmer/xandikos/issues/8
