### ISSUE TITLE
Error 500 with Baikal server: "Trying to access array offset on value of type bool"

### ISSUE THREAD

**Issue by telec16** [python-caldav/caldav#116] opened 2020-10-19 20:09 UTC
I have set up a working Baikal server (v. 0.7.1), I can use it properly with other clients.
But when I try with caldav (also v. 0.7.1), I can't get the stored event with `results = calendar.events()` or with `date_search`, but I totally can add new events (and see them on another client).

Here is the error stack:
```
Traceback (most recent call last):
  File "converter.py", line 40, in <module>
    results = calendar.events()
  File "C:\ProgramData\Anaconda3\lib\site-packages\caldav\objects.py", line 845, in events
    return self.search(root, comp_class=Event)
  File "C:\ProgramData\Anaconda3\lib\site-packages\caldav\objects.py", line 612, in search
    response = self._query(xml, 1, 'report')
  File "C:\ProgramData\Anaconda3\lib\site-packages\caldav\objects.py", line 171, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.ReportError: 500 Internal Server Error

b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:sabredav-version>4.1.0</s:sabredav-version>\n  <s:exception>ErrorException</s:exception>\n  <s:message>Trying to access array offset on value of type bool</s:message>\n</d:error>\n' ```

Any idea why?

**Comment by tobixen** [comment] 2020-10-19 22:09
First, "500 Internal Server Error" hints that the problem is at the baikal side (and if the problem is at our side, then the baikal team ought to fix better error handling).  Please try to raise an issue with the Baikal team.

That said, I should try to set up a baikal server and run the tests code towards them to see if I can spot any compatibility issues ... and I should make notes in `tests/compatibility_issues.py` on what versions of the library that have been successfully tested towards which versions of what servers.  Perhaps I will have time for it this week or the next - but anyway, please try to raise an issue with the Baikal team.

**Comment by telec16** [comment] 2020-10-21 17:54
Thanks for your quick answer!
As Baikal is working with other clients, I thought at first that it was caldav fault... But when I tap into the request method, it (caldav) sends
```xml
<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT"/>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
```
Which seems to be exactly what Baikal is waiting for (https://sabre.io/dav/building-a-caldav-client/#downloading-objects)...

So caldav doesn't seem to be the problem here. I will raise an issue with the Baikal team.

**Comment by tobixen** [comment] 2020-11-23 01:20
The `events()`-method above will fetch all objects in the calendar and not only events.

In master, there is a new method objects_by_sync_token that can be used for fetching all objects.

**Comment by tobixen** [comment] 2020-11-23 01:21
I'll close this issue since it's (more or less) resolved.

**Closed by tobixen** 2020-11-23 01:21 UTC
